% This test file was generated by Copilot. Validate generated output before use.
classdef SimulationModelTest < matlab.unittest.TestCase
    properties
        model
    end

    methods(TestMethodSetup)
        function createModel(testCase)
            testCase.model = SimulationModel();
        end
    end

    methods(Test)
        function testInitialValues(testCase)
            testCase.verifyEqual(testCase.model.Kel0, testCase.model.SimFun.Parameters.Value(1));
            testCase.verifyEqual(testCase.model.Kon0, testCase.model.SimFun.Parameters.Value(2));
            testCase.verifyEqual(testCase.model.Kdeg0, testCase.model.SimFun.Parameters.Value(3));
            testCase.verifyEqual(testCase.model.Duration0, 119);
            testCase.verifyEqual(testCase.model.Interval0, testCase.model.DoseTable.Interval);
            testCase.verifyEqual(testCase.model.Amount0, testCase.model.DoseTable.Amount);
        end

        function testSimulateWithDefaultParameters(testCase)
            testCase.model.simulate();
            testCase.verifyNotEmpty(testCase.model.SimData);
            testCase.verifyNotEmpty(testCase.model.SimDataTable);
            testCase.verifyLessThanOrEqual(height(testCase.model.SimDataTable), ...
                height(testCase.model.SimData.Time));
        end

        function testROIsBetweenThresholds(testCase)
            testCase.model.simulate();
            roiValue = testCase.model.ROIsBetweenThresholds;
            testCase.verifyClass(roiValue, "logical");
        end

        function testSimulateWithCustomParameters(testCase)
            customParams = [0.1, 0.2, 0.3, 120, 50, 24]; % example parameters
            testCase.model.simulate(customParams);
            testCase.verifyEqual(testCase.model.DoseTable.Amount, customParams(5));
            testCase.verifyEqual(testCase.model.DoseTable.Interval, customParams(6));
        end
    end
end