% This is an autogenerated sample test for file ismember
classdef tSimulationModel < matlab.unittest.TestCase
    methods (Test)
        function test_ismember(testCase)
            % Specify the input(s) of ismember
            sObj = SimulationModel;
            simulate(sObj);
            testCase.verifyClass(sObj.SimData, 'SimData');

            % Exercise the function ismember
            actualOutput = ismember(sObj.SimData.DataNames,["Drug","Receptor","Complex","RO"]);

            % Specify the expected output(s) of ismember
            expectedOutput = true(size(sObj.SimData.DataNames));

            testCase.verifyEqual(actualOutput, expectedOutput);
        end
    end
end