% This is an autogenerated sample test for file all
classdef ttesttest < matlab.unittest.TestCase
    methods (Test)
        function test_all(testCase)
            % Specify the input(s) of all
            sObj = SimulationModel;

            sObj.simulate();

            % Exercise the function all
            actualOutput = all(ismember(sObj.SimData.DataNames,["Drug","Receptor","Complex","RO"]));

            % Specify the expected output(s) of all
            expectedOutput = true;

            testCase.verifyEqual(actualOutput, expectedOutput);
        end
    end
end